version: '3'

services:
  nginx:
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: xxx.example.com
      LETSENCRYPT_HOST: xxx.example.com
      LETSENCRYPT_EMAIL: contact@xxx.example.com

networks:
  default:
    external:
      name: nginx-proxy
