version: '3'

services:
  nginx:
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: bitwarden.example.com
      LETSENCRYPT_HOST: bitwarden.example.com
      LETSENCRYPT_EMAIL: contact@example.com

networks:
  default:
    external:
      name: nginx-proxy
