version: '3'

networks:
  nginx-proxy:
    external: true

services:
  proxy:
    image: nginx:1.19
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /apps/bitwarden/bwdata/ssl:/etc/ssl
      - /apps/bitwarden/custom:/usr/custom-content/bitwarden
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - /apps/letsencrypt/etc:/etc/letsencrypt
    networks:
      - nginx-proxy
    restart: always
