version: '3'

networks:
  nginx-proxy:
    external: true
  db:

services:
  mysql:
    image: mariadb:10.4
    restart: always
    env_file:
      - ./config/my_env
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - db

  redis:
    image: redis:5
    restart: always
    volumes:
      - ./redis/data:/data
    networks:
      - db

  mongo:
    image: mongo:4-xenial
    restart: always
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - db

  mailtrain:
    image: mailtrain/mailtrain:latest
    restart: always
    env_file:
      - ./config/mt_env
    volumes:
      - ./mailtrain/files:/app/server/files
    networks:
      - db
      - nginx-proxy
