version: '3.1'

networks:
  nginx-proxy:
    external: true
  db:

services:
  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: dbpass
      WORDPRESS_DB_NAME: dbname
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - db
      - nginx-proxy
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: dbrootpass
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - db
